#include "CppUTest/TestHarness.h"
#include "CustomSeqAligner.h"
#include "ReverseCustomSeqAligner.h"

#include <algorithm>

TEST_GROUP(SequenceAligner)
{
    std::string s1, s2, s1_rev, s2_rev;
    ISequenceAligner *pSeqAligner, *pSeqAligner2;

    void setup()
    {
        s1 = "GGGTTGGGGGTAAGGTCACAGATCCACAGGATCCCATGGCAGAAGAATTTTTCTTAGTACAGAACAAAATGAAAAGTCTCCCATGTCTACTTCTTTCTACACAGACACGGCAACCATCCG"
                "ATTTCTCAATCTTTTCCCCACCTTTCCCCCCTTTCTATTCCACAAAACCGCCATTGTCATCATGGCGCGTTCTCAATGAGCTGTTGGGTACACCTCCCAGACGGGGTGGTGGCTGGGCAG"
                "AGGGGCTCCTCACTTCCCAGTAGGGGCGGCCGGGCAGAGGCGCCCCTCACCTCCCGGACGGGGCGGCTGGCCGGGCGGGGGGCTGACCACCCCCACCTCCCTCCCGGACGGGGCGGCTGG"
                "CCGGGCGGGGGGCTGACCCCCCACCTCCCTCCCAGACAGGGCGGCTGGCCGGGCTGGGGGCTGACCCCCCCACCTCCCTCCCAGACGGGGCGGCTGGCCGGGTGGGGGGCTGACCACCCC"
                "CACCTCCCTCCCGGACGGGGCGGCTGGCCGGGCTGAGGGCTGACCCCCCACCTCCCTCCCGGACAGGGTAGCTGCCGGGCAGAGACACTCCTCACTTCCCAGACGGGGTGGTTGCCGGGC"
                "GGAGGGGCTCCTCACTTCTCAGGCGGGGCGGCTGCCGGGCGGAGGGGCT";

        s2 = "CAAGCATCTGTTTAACAAAGCACATCTTGCACCGCCATTAATCCATTTAACCCTGAGTGGACACAGAACATGTTTCAGAGAGCACCGGGTTGGGGGTAAGGTCACAGATACACAGGATC"
                "CCCCTCCCTCCCGGACGGGGCGGCTGGCCGG";

        reverse_copy(begin(s1), end(s1), back_inserter(s1_rev));
        reverse_copy(begin(s2), end(s2), back_inserter(s2_rev));

        pSeqAligner = new CustomSeqAligner();
        pSeqAligner2 = new ReverseCustomSeqAligner(new CustomSeqAligner());

    }
    void teardown()
    {
        delete pSeqAligner;
        delete pSeqAligner2;
    }
};

TEST(SequenceAligner, CustomSeqAlignerAlign)
{
    ScoreParam sParam(2, -3, -10000);

    AlignmentResult actual = pSeqAligner->Align(s1, s2, sParam);

    CHECK_EQUAL(59, actual.GetScore());

    CHECK(Interval(118, 149) == actual.GetAlignmentFragment1().GetMatch2());

}

TEST(SequenceAligner, ReverseCustomSeqAlignerAlign)
{
    ScoreParam sParam(2, -3, -10000);

    AlignmentResult actual = pSeqAligner2->Align(s1_rev, s2_rev, sParam);

    CHECK(Interval(0, 31) == actual.GetAlignmentFragment1().GetMatch2());

}

TEST(SequenceAligner, PrefixAlignerIssue1)
{
    std::string s11 = "TGCTTTTATACGTGACATGCATGGACACAGCAGCCTCTAAATATCTTGACATTTTTCTCTCGTAAGCAGAATCACTAACATTTTATTGAGTATAACTTTT"
            "TTAGCTAATTCCCTCACCGTTTTATGTGGTAAAAGTCACTATTTTCCTTGGGAGCAGAGCAGGCCGTGAACCCAGGTCTGTCTGCTTTGAAACACATTCA"
            "CACTGTACTGCCACTGGGTAATGATGGGAAACAAAATTATTCCTTCAAATCAGGTGCTAATTCTTCTCAAATCATCATCATCACCACCATCATCATCATC"
            "ATCATCATCACCACCATCATCATTTCATCAGGCCTCAAAAGTTTACCTGCATGATTTACTTTGACCCTAACCATATTTTCCACCTGTTTCCTAGGAGTCT"
            "TTTCCAGTATTCCTCTGTACTCCTCCCTCTCTCAGCCCATAGAGTCGCAATACACAATTATGGCTTCTTTATGTTTCACCTCTTGTTGTTCACTATGCTT"
            "TTATGTTTCCTTATCTCCTCCTCCCAGTCAGACTGTCCAGTCTTTGAGGGTGTAAATCATGTGTCCACCACAAAGCTGGGGCTGTGGGTACCACATGGGC"
            "TGTCCCCAGCCCATGTAGCACCTGCCAGGGCTCTGCACATCTCATCAAGAGCTG";
    std::string s22 = "TGGGAAACAAAATTATTCCTTCAAATCAGGTGCTAATTCTTCTCAAATCTTTCACCTCTTGTTGTTCACTATGCTTTTATGTTTCCTTATCTCCTCCTCC"
            "CAGTCAGACTGTCCAGTCTTTGAGGGTGTAAATCATGTGTCCACCACAAA";

    ScoreParam sParam(2, -3, -5);
    AlignmentResult actual = pSeqAligner2->Align(s11, s22, sParam);

    actual.GetAlignmentFragment1().PrintAlignment();

    std::cout << actual.GetAlignmentFragment1().GetMatch2Length() << std::endl;
    std::cout << actual.GetAlignmentFragment1().GetPercentageIdentity() << std::endl;
}
